Numpy

In [1]:
import numpy as np

In [ ]:
##Creating a 1D Array (Vector)
#A NumPy array is like a vector in mathematics or R.

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [3]:
##Creating a 2D Array (Matrix)
#A 2D array represents a matrix with rows and columns.

b = np.array([[1, 2], [3, 4]])
print(b)

[[1 2]
 [3 4]]


In [19]:
##Mathematical Operations
#Perform element-wise addition and multiplication.
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)
print(x * y)

np.dot(x, y)
int(np.dot(x, y))

[5 7 9]
[ 4 10 18]


32

In [7]:
##Broadcasting
#Add a scalar to all elements of an array.
x = np.array([1, 2, 3])

print(x + 5)

[6 7 8]


In [8]:
##Statistical Functions
#Calculate mean, variance, and standard deviation.

data = np.array([2, 4, 6, 8])

print(np.mean(data))
print(np.var(data))
print(np.std(data))

5.0
5.0
2.23606797749979


In [20]:
##Indexing
#Access specific elements (Python uses 0-based indexing).

x = np.array([10, 20, 30, 40])

print(x[0])
print(x[2])

#Negative Indexing
x = np.array([10, 20, 30, 40])

print(x[-1])
print(x[-2])

10
30
40
30


In [10]:
##Slicing
#Extract a subset of elements from an array.
x = np.array([10, 20, 30, 40, 50])

print(x[1:4])

[20 30 40]


In [ ]:
##Matrix Indexing (2D Indexing)
#Access elements from a 2D array using row and column indices.

A = np.array([[1, 2], [3, 4]])

print(A[0, 1])

2


In [21]:
##3D Indexing (Tensor)

arr = np.arange(27)
arr_3d = arr.reshape(3,3,3)

print(arr_3d[2,0,2])

20


In [ ]:
##Reshaping Arrays
#Change the shape of an array (vector to matrix).

x = np.array([1, 2, 3, 4, 5, 6])

y = x.reshape(2, 3)
print(y)

[[1 2 3]
 [4 5 6]]


In [13]:
##Shape and Dimension
#Get size, shape, and dimensions of an array.

x = np.array([[1, 2, 3], [4, 5, 6]])

print(x.shape)
print(x.ndim)
print(x.size)

(2, 3)
2
6


In [14]:
##Random Number Generation
#Generate random numbers for simulations and statistical analysis.

print(np.random.rand(5))        # Uniform distribution
print(np.random.randn(5))       # Normal distribution
print(np.random.randint(1, 10, 5))

[0.14651371 0.02298862 0.15218422 0.33078652 0.84157434]
[ 0.4865714  -1.38679638  1.60316992  0.2560089   1.79383962]
[5 9 2 6 8]


In [1]:
##Random Number generation using inverse theorem

import numpy as np

U = np.random.rand(5)
X = -np.log(1 - U)

print(X)

[1.10271781 0.24334566 2.19405121 0.00666559 2.0898266 ]


In [ ]:
##PRNG

np.random.seed(42)   # set seed
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


In [15]:
##Creating Sequences
#Generate sequences similar to R's seq() function.
print(np.arange(1, 10, 2))
print(np.linspace(0, 1, 5))

[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]
